/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A simple FOSDEM-specific JSON format to describe the schedule for a FOSDEM conference driven by conference-bot.
 */
export interface FOSDEMSpecificJSONSchedule {
  talks: FOSDEMTalk[];
  tracks: FOSDEMTrack[];
  [k: string]: unknown;
}
/**
 * Information about a scheduled talk
 */
export interface FOSDEMTalk {
  /**
   * Unique ID for the talk
   */
  event_id: number;
  /**
   * Human-readable name for the talk
   */
  title: string;
  /**
   * Date and time, in RFC3339 format with Z timezone offset, of the start of the talk
   */
  start_datetime: string;
  /**
   * Duration of the talk, in minutes
   */
  duration: number;
  persons: FOSDEMPerson[];
  /**
   * Information about what track the talk is in. N.B. In practice more fields are contained here but only ID is used.
   */
  track: {
    /**
     * The Track ID of the track that the talk is in
     */
    id: number;
    /**
     * Whether online question & answer support is enabled for this track.
     */
    online_qa: boolean;
    [k: string]: unknown;
  };
  /**
   * System name (not human-friendly) of the physical (in real life) room that the talk is held in. e.g. `ud2218a`
   */
  conference_room: string;
  [k: string]: unknown;
}
/**
 * Information about someone who is giving a talk or is assisting with co-ordination
 */
export interface FOSDEMPerson {
  /**
   * ID of the person
   */
  person_id: number;
  /**
   * What kind of role the person has for this talk (speaker/coordinator)
   */
  event_role: string;
  /**
   * The name of the person
   */
  name: string;
  /**
   * The e-mail address of the person. May be an empty string if not available.
   */
  email: string;
  /**
   * The Matrix User ID of the person. May be an empty string if not available. Has historically not been validated thoroughly.
   */
  matrix_id: string;
  [k: string]: unknown;
}
/**
 * Information about a sequence of talks
 */
export interface FOSDEMTrack {
  /**
   * Stable ID for the track
   */
  id: number;
  /**
   * Stable semi-human-readable slug for the track
   */
  slug: string;
  /**
   * Human-readable name of the track
   */
  name: string;
  /**
   * 'devroom' or 'maintrack' (TODO encode this in schema)
   */
  type: string;
  /**
   * List of staff (co-ordinators right now) that apply to the entire track.
   */
  managers: FOSDEMPerson[];
  [k: string]: unknown;
}
