name: Build Docker Image

on:
  push:

env:
  PLATFORMS: linux/amd64

jobs:
  docker-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: false
          tags: |
            matrixdotorg/conf-bot:latest